// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAltP5oAw9x90iQZmgkiCuUt9g-bmRdYWk',
    appId: '1:95695539959:web:96bfa6ed48eb244eee0df2',
    messagingSenderId: '95695539959',
    projectId: 'instagram-app-808af',
    authDomain: 'instagram-app-808af.firebaseapp.com',
    storageBucket: 'instagram-app-808af.appspot.com',
  );

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAn0wwCTrs4lXX17rbOzKLujOwPs0GDs6A',
  appId: '1:95695539959:android:9af1044132f3fe1cee0df2',
  messagingSenderId: '95695539959',
  projectId: 'instagram-app-808af',
  storageBucket: 'instagram-app-808af.appspot.com',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90qFgEhHzeiaF6_H58iC2FvU4qoCJt6g',
    appId: '1:95695539959:ios:ba0c137cf02bb22aee0df2',
    messagingSenderId: '95695539959',
    projectId: 'instagram-app-808af',
    storageBucket: 'instagram-app-808af.appspot.com',
    iosBundleId: 'com.example.LedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90qFgEhHzeiaF6_H58iC2FvU4qoCJt6g',
    appId: '1:95695539959:ios:ba0c137cf02bb22aee0df2',
    messagingSenderId: '95695539959',
    projectId: 'instagram-app-808af',
    storageBucket: 'instagram-app-808af.appspot.com',
    iosBundleId: 'com.example.LedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAltP5oAw9x90iQZmgkiCuUt9g-bmRdYWk',
    appId: '1:95695539959:web:0f6e0587410252b8ee0df2',
    messagingSenderId: '95695539959',
    projectId: 'instagram-app-808af',
    authDomain: 'instagram-app-808af.firebaseapp.com',
    storageBucket: 'instagram-app-808af.appspot.com',
  );

}